/**
 * BoardPack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoardPack DTOs
 *
 * DDD: Application DTOs for BoardPack use cases.
 */

import type { CreateBoardPackRequestInput, GetBoardPackParams, ListBoardPacksParams } from "@portiva/core/board-pack/types";

export type ListBoardPacksInput = ListBoardPacksParams;

export type CreateBoardPackInput = CreateBoardPackRequestInput;

export type GetBoardPackInput = GetBoardPackParams;

export type ListBoardPacksOutput = {};

export type CreateBoardPackOutput = {};

export type GetBoardPackOutput = {};
