/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@portiva/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildBoardPackDomainModule,
  buildDecisionDomainModule,
  buildDependencyDomainModule,
  buildGateDomainModule,
  buildIdentityDomainModule,
  buildInitiativeDomainModule,
  buildOverlapDomainModule,
  buildPolicyWatchDomainModule,
  buildScorecardDomainModule,
} from "../domains/index.js";
import type {
  BoardPackDomainModule,
  DecisionDomainModule,
  DependencyDomainModule,
  GateDomainModule,
  IdentityDomainModule,
  InitiativeDomainModule,
  OverlapDomainModule,
  PolicyWatchDomainModule,
  ScorecardDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private boardPackModule: BoardPackDomainModule | null = null;
  private decisionModule: DecisionDomainModule | null = null;
  private dependencyModule: DependencyDomainModule | null = null;
  private gateModule: GateDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private initiativeModule: InitiativeDomainModule | null = null;
  private overlapModule: OverlapDomainModule | null = null;
  private policyWatchModule: PolicyWatchDomainModule | null = null;
  private scorecardModule: ScorecardDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get board-pack domain module
   */
  getBoardPackDependencies(): BoardPackDomainModule {
    if (!this.boardPackModule) {
      this.boardPackModule = buildBoardPackDomainModule(this.dynamoClient);
    }
    return this.boardPackModule;
  }

  /**
   * Get decision domain module
   */
  getDecisionDependencies(): DecisionDomainModule {
    if (!this.decisionModule) {
      this.decisionModule = buildDecisionDomainModule(this.dynamoClient);
    }
    return this.decisionModule;
  }

  /**
   * Get dependency domain module
   */
  getDependencyDependencies(): DependencyDomainModule {
    if (!this.dependencyModule) {
      this.dependencyModule = buildDependencyDomainModule(this.dynamoClient);
    }
    return this.dependencyModule;
  }

  /**
   * Get gate domain module
   */
  getGateDependencies(): GateDomainModule {
    if (!this.gateModule) {
      this.gateModule = buildGateDomainModule(this.dynamoClient);
    }
    return this.gateModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get initiative domain module
   */
  getInitiativeDependencies(): InitiativeDomainModule {
    if (!this.initiativeModule) {
      this.initiativeModule = buildInitiativeDomainModule(this.dynamoClient);
    }
    return this.initiativeModule;
  }

  /**
   * Get overlap domain module
   */
  getOverlapDependencies(): OverlapDomainModule {
    if (!this.overlapModule) {
      this.overlapModule = buildOverlapDomainModule(this.dynamoClient);
    }
    return this.overlapModule;
  }

  /**
   * Get policy-watch domain module
   */
  getPolicyWatchDependencies(): PolicyWatchDomainModule {
    if (!this.policyWatchModule) {
      this.policyWatchModule = buildPolicyWatchDomainModule(this.dynamoClient);
    }
    return this.policyWatchModule;
  }

  /**
   * Get scorecard domain module
   */
  getScorecardDependencies(): ScorecardDomainModule {
    if (!this.scorecardModule) {
      this.scorecardModule = buildScorecardDomainModule(this.dynamoClient);
    }
    return this.scorecardModule;
  }

  clearBoardPackDependencies(): void { this.boardPackModule = null; }
  clearDecisionDependencies(): void { this.decisionModule = null; }
  clearDependencyDependencies(): void { this.dependencyModule = null; }
  clearGateDependencies(): void { this.gateModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearInitiativeDependencies(): void { this.initiativeModule = null; }
  clearOverlapDependencies(): void { this.overlapModule = null; }
  clearPolicyWatchDependencies(): void { this.policyWatchModule = null; }
  clearScorecardDependencies(): void { this.scorecardModule = null; }

  getBoardPackDependenciesForRequest(): BoardPackDomainModule {
    return this.getBoardPackDependencies();
  }

  getDecisionDependenciesForRequest(): DecisionDomainModule {
    return this.getDecisionDependencies();
  }

  getDependencyDependenciesForRequest(): DependencyDomainModule {
    return this.getDependencyDependencies();
  }

  getGateDependenciesForRequest(): GateDomainModule {
    return this.getGateDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getInitiativeDependenciesForRequest(): InitiativeDomainModule {
    return this.getInitiativeDependencies();
  }

  getOverlapDependenciesForRequest(): OverlapDomainModule {
    return this.getOverlapDependencies();
  }

  getPolicyWatchDependenciesForRequest(): PolicyWatchDomainModule {
    return this.getPolicyWatchDependencies();
  }

  getScorecardDependenciesForRequest(): ScorecardDomainModule {
    return this.getScorecardDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.boardPackModule = null;
    this.decisionModule = null;
    this.dependencyModule = null;
    this.gateModule = null;
    this.identityModule = null;
    this.initiativeModule = null;
    this.overlapModule = null;
    this.policyWatchModule = null;
    this.scorecardModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
