/**
 * ExecuteUpsertScorecard - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpsertScorecard Use Case
 *
 * DDD: Application use case for get Scorecard.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpsertScorecardInput, UpsertScorecardOutput } from "../dto/scorecard.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { ScorecardRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteUpsertScorecard {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scorecard: ScorecardRepository
  ) {}

  async execute(input: UpsertScorecardInput): Promise<UpsertScorecardOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.scorecard.upsertScorecard({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as UpsertScorecardOutput;
  }
}
