/**
 * ExecuteGetScorecardByInitiative - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetScorecardByInitiative Use Case
 *
 * DDD: Application use case for get Scorecard.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetScorecardByInitiativeInput, GetScorecardByInitiativeOutput } from "../dto/scorecard.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { ScorecardRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetScorecardByInitiative {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scorecard: ScorecardRepository
  ) {}

  async execute(input: GetScorecardByInitiativeInput): Promise<GetScorecardByInitiativeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).initiativeId) {
      throw new ValidationError("initiativeId is required");
    }
    const initiativeId = (input as any).initiativeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.scorecard.getScorecardByInitiative({ initiativeId: initiativeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${initiativeId}`);
    }

    return entity as GetScorecardByInitiativeOutput;
  }
}
