/**
 * ExecuteGetScorecard - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetScorecard Use Case
 *
 * DDD: Application use case for get Scorecard.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetScorecardInput, GetScorecardOutput } from "../dto/scorecard.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { ScorecardRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetScorecard {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scorecard: ScorecardRepository
  ) {}

  async execute(input: GetScorecardInput): Promise<GetScorecardOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).scorecardId) {
      throw new ValidationError("scorecardId is required");
    }
    const scorecardId = (input as any).scorecardId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.scorecard.getScorecard({ scorecardId: scorecardId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${scorecardId}`);
    }

    return entity as GetScorecardOutput;
  }
}
