/**
 * ExecuteListScorecards - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListScorecards Use Case
 *
 * DDD: Application use case for list Scorecard.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListScorecardsInput, ListScorecardsOutput } from "../dto/scorecard.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { ScorecardRepository } from "../ports";

export class ExecuteListScorecards {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scorecard: ScorecardRepository
  ) {}

  async execute(input: ListScorecardsInput): Promise<ListScorecardsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.scrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.scorecard.listScorecards({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListScorecardsOutput;
  }
}
