/**
 * Handlers for Initiative
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InitiativeDomainModule } from "../dependencies/initiative-ddd.dependencies.js";
import type { CreateInitiativeInput, GetInitiativeInput, ListInitiativesInput, UpdateInitiativeInput } from "@portiva/services/initiative";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/initiatives
 * Operation: listInitiatives
 */
export async function listInitiatives(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], arc?: string | string[], stage?: string | string[], status?: string | string[], sponsorUserId?: string | string[], overlapFlag?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: InitiativeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListInitiativesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.initiatives.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/initiatives
 * Operation: createInitiative
 */
export async function createInitiative(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: InitiativeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateInitiativeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.initiatives.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/initiatives/{initiativeId}
 * Operation: getInitiative
 */
export async function getInitiative(
  request: FastifyRequest<{ Params: { initiativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: InitiativeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetInitiativeInput = {
    initiativeId: request.params.initiativeId,
  };
  const result = await deps.useCases.initiatives.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/initiatives/{initiativeId}
 * Operation: updateInitiative
 */
export async function updateInitiative(
  request: FastifyRequest<{ Params: { initiativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: InitiativeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateInitiativeInput = {
    initiativeId: request.params.initiativeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.initiatives.update.execute(input);
  return reply.code(200).send(result);
}


