/**
 * DecisionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DecisionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DecisionRepository,
} from "@portiva/services/decision";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DecisionRepositoryDdb } from "./decision-repository.ddb.js";

/**
 * DecisionRepositoryAdapter
 *
 * Implements DecisionRepository port for infrastructure layer.
 */
export class DecisionRepositoryAdapter implements DecisionRepository {
  private readonly ddb: DecisionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DecisionRepositoryDdb(this.dynamoClient);
  }

  async listFundingDecisions(input: Parameters<DecisionRepository['listFundingDecisions']>[0]): Promise<Awaited<ReturnType<DecisionRepository['listFundingDecisions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFundingDecisions(input);
  }

  async createFundingDecision(input: Parameters<DecisionRepository['createFundingDecision']>[0]): Promise<Awaited<ReturnType<DecisionRepository['createFundingDecision']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createFundingDecision(input);
  }

  async getFundingDecision(input: Parameters<DecisionRepository['getFundingDecision']>[0]): Promise<Awaited<ReturnType<DecisionRepository['getFundingDecision']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFundingDecision(input);
  }
}
