/**
 * Scorecard DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Scorecard Domain Module - Composition root
 *
 * DDD: Composition root for scorecard domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ScorecardRepositoryAdapter,
} from "@portiva/adapters/scorecard";
import { getIdGeneratorService } from "@portiva/adapters";
import type { AdapterDynamoDBClient } from "@portiva/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetScorecard,
  ExecuteGetScorecardByInitiative,
  ExecuteListScorecards,
  ExecuteUpsertScorecard,
} from "@portiva/services/scorecard/usecases";
// Ports (interfaces)
import type {
  ScorecardRepository,
} from "@portiva/services/scorecard/ports";

export interface ScorecardDomainModule {
  repos: {
    scorecards: ScorecardRepository;
  };
  useCases: {
    scorecards: {
      get: ExecuteGetScorecardByInitiative;
      list: ExecuteListScorecards;
    };
  };
}

export function buildScorecardDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ScorecardDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      scorecards?: ScorecardRepository;
    } = {};

    obj.scorecards = new ScorecardRepositoryAdapter(dynamoClient);
    return {
      scorecards: obj.scorecards!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    scorecards: {
      get: new ExecuteGetScorecardByInitiative(executionContext, idGenerator, repos.scorecards),
      list: new ExecuteListScorecards(executionContext, idGenerator, repos.scorecards),
    },
  };
  return { repos, useCases: useCases as ScorecardDomainModule["useCases"] };
}
