/**
 * BoardPack DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoardPack Domain Module - Composition root
 *
 * DDD: Composition root for board-pack domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BoardPackRepositoryAdapter,
} from "@portiva/adapters/board-pack";
import { getIdGeneratorService } from "@portiva/adapters";
import type { AdapterDynamoDBClient } from "@portiva/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateBoardPack,
  ExecuteGetBoardPack,
  ExecuteListBoardPacks,
} from "@portiva/services/board-pack/usecases";
// Ports (interfaces)
import type {
  BoardPackRepository,
} from "@portiva/services/board-pack/ports";

export interface BoardPackDomainModule {
  repos: {
    boardPacks: BoardPackRepository;
  };
  useCases: {
    boardPacks: {
      create: ExecuteCreateBoardPack;
      get: ExecuteGetBoardPack;
      list: ExecuteListBoardPacks;
    };
  };
}

export function buildBoardPackDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): BoardPackDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      boardPacks?: BoardPackRepository;
    } = {};

    obj.boardPacks = new BoardPackRepositoryAdapter(dynamoClient);
    return {
      boardPacks: obj.boardPacks!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    boardPacks: {
      create: new ExecuteCreateBoardPack(executionContext, idGenerator, repos.boardPacks),
      get: new ExecuteGetBoardPack(executionContext, idGenerator, repos.boardPacks),
      list: new ExecuteListBoardPacks(executionContext, idGenerator, repos.boardPacks),
    },
  };
  return { repos, useCases: useCases as BoardPackDomainModule["useCases"] };
}
