/**
 * GetVendorDependency handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependency
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getVendorDependency } from "@portiva/api-server/domains/dependency/handlers";
import type { DependencyDDDDependencies } from "@portiva/api-server/domains/dependency";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { DEPENDENCY_USE_CASES } from "../__factories__/use-cases.js";

describe("GetVendorDependency", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DependencyDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DependencyDDDDependencies>(
      DEPENDENCY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetVendorDependency, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { dependencyId: entity.id };

    await getVendorDependency(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetVendorDependency.execute).toHaveBeenCalledWith(expect.objectContaining({ dependencyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { dependencyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetVendorDependency, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getVendorDependency(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
