/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependency
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-vendor-dependency.handler.test.js";
export * from "./get-vendor-dependency.handler.test.js";
export * from "./list-vendor-dependencies.handler.test.js";
