/**
 * Handlers for BoardPack
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BoardPackDomainModule } from "../dependencies/board-pack-ddd.dependencies.js";
import type { CreateBoardPackInput, GetBoardPackInput, ListBoardPacksInput } from "@portiva/services/board-pack";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/board-packs
 * Operation: listBoardPacks
 */
export async function listBoardPacks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], period?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: BoardPackDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListBoardPacksInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.boardPacks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/board-packs
 * Operation: createBoardPack
 */
export async function createBoardPack(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: BoardPackDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateBoardPackInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.boardPacks.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/board-packs/{boardPackId}
 * Operation: getBoardPack
 */
export async function getBoardPack(
  request: FastifyRequest<{ Params: { boardPackId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BoardPackDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetBoardPackInput = {
    boardPackId: request.params.boardPackId,
  };
  const result = await deps.useCases.boardPacks.get.execute(input);
  return reply.code(200).send(result);
}


