/**
 * Initiative DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Initiative Domain Module - Composition root
 *
 * DDD: Composition root for initiative domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  InitiativeRepositoryAdapter,
} from "@portiva/adapters/initiative";
import { getIdGeneratorService } from "@portiva/adapters";
import type { AdapterDynamoDBClient } from "@portiva/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateInitiative,
  ExecuteGetInitiative,
  ExecuteListInitiatives,
  ExecuteUpdateInitiative,
} from "@portiva/services/initiative/usecases";
// Ports (interfaces)
import type {
  InitiativeRepository,
} from "@portiva/services/initiative/ports";

export interface InitiativeDomainModule {
  repos: {
    initiatives: InitiativeRepository;
  };
  useCases: {
    initiatives: {
      create: ExecuteCreateInitiative;
      get: ExecuteGetInitiative;
      list: ExecuteListInitiatives;
      update: ExecuteUpdateInitiative;
    };
  };
}

export function buildInitiativeDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): InitiativeDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      initiatives?: InitiativeRepository;
    } = {};

    obj.initiatives = new InitiativeRepositoryAdapter(dynamoClient);
    return {
      initiatives: obj.initiatives!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    initiatives: {
      create: new ExecuteCreateInitiative(executionContext, idGenerator, repos.initiatives),
      get: new ExecuteGetInitiative(executionContext, idGenerator, repos.initiatives),
      list: new ExecuteListInitiatives(executionContext, idGenerator, repos.initiatives),
      update: new ExecuteUpdateInitiative(executionContext, idGenerator, repos.initiatives),
    },
  };
  return { repos, useCases: useCases as InitiativeDomainModule["useCases"] };
}
