/**
 * Initiative DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Initiative DTOs
 *
 * DDD: Application DTOs for Initiative use cases.
 */

import type { CreateInitiativeRequestInput, GetInitiativeParams, ListInitiativesParams, UpdateInitiativeParams, UpdateInitiativeRequestInput } from "@portiva/core/initiative/types";

export type ListInitiativesInput = ListInitiativesParams;

export type CreateInitiativeInput = CreateInitiativeRequestInput;

export type GetInitiativeInput = GetInitiativeParams;

export type UpdateInitiativeInput = UpdateInitiativeParams & UpdateInitiativeRequestInput;

export type ListInitiativesOutput = {};

export type CreateInitiativeOutput = {};

export type GetInitiativeOutput = {};

export type UpdateInitiativeOutput = {};
