/**
 * BoardPack Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { BoardPackEntity } from "@portiva/core/board-pack/models/index.js";
import { boardPackSchemas } from "@portiva/core/board-pack";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "brd";

export function createBoardPack(overrides: Partial<BoardPackEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    boardPackId: overrides.boardPackId ?? `brd_${ulid().toLowerCase()}`,
    expectedValue: overrides.expectedValue ?? faker.number.int(),
    period: overrides.period ?? faker.lorem.word(),
    riskSummary: overrides.riskSummary ?? faker.lorem.word(),
    spendTotal: overrides.spendTotal ?? faker.number.int(),
    stageDistribution: overrides.stageDistribution ?? {},
    status: overrides.status ?? "draft",
    ...overrides,
  };

  return boardPackSchemas.BoardPack.parse(raw);
}

export function boardPackBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createBoardPack(overrides));
}
