/**
 * ExecuteGetPolicyWatchItem - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-watch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPolicyWatchItem Use Case
 *
 * DDD: Application use case for get PolicyWatch.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPolicyWatchItemInput, GetPolicyWatchItemOutput } from "../dto/policy-watch.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { PolicyWatchRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPolicyWatchItem {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policyWatch: PolicyWatchRepository
  ) {}

  async execute(input: GetPolicyWatchItemInput): Promise<GetPolicyWatchItemOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyWatchId) {
      throw new ValidationError("policyWatchId is required");
    }
    const policywatchId = (input as any).policyWatchId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.policyWatch.getPolicyWatchItem({ policyWatchId: policywatchId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${policywatchId}`);
    }

    return entity as GetPolicyWatchItemOutput;
  }
}
