/**
 * ExecuteListPolicyWatchItems - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-watch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPolicyWatchItems Use Case
 *
 * DDD: Application use case for list PolicyWatch.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPolicyWatchItemsInput, ListPolicyWatchItemsOutput } from "../dto/policy-watch.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { PolicyWatchRepository } from "../ports";

export class ExecuteListPolicyWatchItems {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policyWatch: PolicyWatchRepository
  ) {}

  async execute(input: ListPolicyWatchItemsInput): Promise<ListPolicyWatchItemsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.policyWatch.listPolicyWatchItems({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPolicyWatchItemsOutput;
  }
}
