/**
 * ExecuteCreatePolicyWatchItem - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-watch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreatePolicyWatchItem Use Case
 *
 * DDD: Application use case for create PolicyWatch.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreatePolicyWatchItemInput, CreatePolicyWatchItemOutput } from "../dto/policy-watch.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { PolicyWatchRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreatePolicyWatchItem {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly policyWatch: PolicyWatchRepository
  ) {}

  async execute(input: CreatePolicyWatchItemInput): Promise<CreatePolicyWatchItemOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.polId();

    // All field names extracted from OpenAPI spec: blocksScale, initiativeIds, thresholdDays, topic
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.initiativeIds) {
      throw new ValidationError("initiativeIds is required");
    }
    if (!input.thresholdDays) {
      throw new ValidationError("thresholdDays is required");
    }
    if (!input.topic) {
      throw new ValidationError("topic is required");
    }
    if (!input.blocksScale) {
      throw new ValidationError("blocksScale is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (policy-watch domain)
    const entityId = this.idGenerator.polId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.policyWatch.createPolicyWatchItem({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreatePolicyWatchItemOutput;
  }
}
