/**
 * KeepDifferentiatedRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KeepDifferentiatedRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements KeepDifferentiatedRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  KeepDifferentiatedRepository,
} from "@portiva/services/overlap";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { KeepDifferentiatedRepositoryDdb } from "./keep-differentiated-repository.ddb.js";

/**
 * KeepDifferentiatedRepositoryAdapter
 *
 * Implements KeepDifferentiatedRepository port for infrastructure layer.
 */
export class KeepDifferentiatedRepositoryAdapter implements KeepDifferentiatedRepository {
  private readonly ddb: KeepDifferentiatedRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new KeepDifferentiatedRepositoryDdb(this.dynamoClient);
  }

  async keepOverlapDifferentiated(input: Parameters<KeepDifferentiatedRepository['keepOverlapDifferentiated']>[0]): Promise<Awaited<ReturnType<KeepDifferentiatedRepository['keepOverlapDifferentiated']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.keepOverlapDifferentiated(input);
  }
}
