/**
 * Repository interface for Initiative
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  InitiativeEntity
} from "../models/initiative.entity.js";
import type {
  ListInitiativesParams,
  Initiative,
  UpdateInitiativeRequestInput
} from "../types/index.js";
/**
 * InitiativeRepository Interface
 */
export interface InitiativeRepository extends CreateUpdateReadRepository<InitiativeEntity, Initiative, UpdateInitiativeRequestInput, string, ListInitiativesParams> {

}
