/**
 * Pass DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pass DTOs
 *
 * DDD: Application DTOs for Pass use cases.
 */

import type { PassStageGateParams, PassStageGateRequestInput } from "@portiva/core/gate/types";

export type PassStageGateInput = PassStageGateParams & PassStageGateRequestInput;

export type PassStageGateOutput = {};
