/**
 * KillOverlapMember handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { killOverlapMember } from "@portiva/api-server/domains/overlap/handlers";
import type { OverlapDDDDependencies } from "@portiva/api-server/domains/overlap";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { OVERLAP_USE_CASES } from "../__factories__/use-cases.js";

describe("KillOverlapMember", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: OverlapDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<OverlapDDDDependencies>(
      OVERLAP_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeKillOverlapMember, "execute").mockResolvedValue(useCaseResult);

    await killOverlapMember(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeKillOverlapMember.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
