/**
 * GetStageGate handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getStageGate } from "@portiva/api-server/domains/gate/handlers";
import type { GateDDDDependencies } from "@portiva/api-server/domains/gate";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { GATE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetStageGate", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GateDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GateDDDDependencies>(
      GATE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetStageGate, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { gateId: entity.id };

    await getStageGate(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetStageGate.execute).toHaveBeenCalledWith(expect.objectContaining({ gateId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { gateId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetStageGate, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getStageGate(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
