/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as boardPackRoutes from "../../domains/board-pack/routes/index.js";
import * as decisionRoutes from "../../domains/decision/routes/index.js";
import * as dependencyRoutes from "../../domains/dependency/routes/index.js";
import * as gateRoutes from "../../domains/gate/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as initiativeRoutes from "../../domains/initiative/routes/index.js";
import * as overlapRoutes from "../../domains/overlap/routes/index.js";
import * as policyWatchRoutes from "../../domains/policy-watch/routes/index.js";
import * as scorecardRoutes from "../../domains/scorecard/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "board-pack", mod: boardPackRoutes },
  { domain: "decision", mod: decisionRoutes },
  { domain: "dependency", mod: dependencyRoutes },
  { domain: "gate", mod: gateRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "initiative", mod: initiativeRoutes },
  { domain: "overlap", mod: overlapRoutes },
  { domain: "policy-watch", mod: policyWatchRoutes },
  { domain: "scorecard", mod: scorecardRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
