/**
 * GetInitiative handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getInitiative } from "@portiva/api-server/domains/initiative/handlers";
import type { InitiativeDDDDependencies } from "@portiva/api-server/domains/initiative";
import { createInitiative as createInitiativeEntity } from "@portiva/factories/initiative";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { INITIATIVE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetInitiative", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InitiativeDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InitiativeDDDDependencies>(
      INITIATIVE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createInitiativeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetInitiative, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { initiativeId: entity.id };

    await getInitiative(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetInitiative.execute).toHaveBeenCalledWith(expect.objectContaining({ initiativeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { initiativeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetInitiative, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getInitiative(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
