/**
 * Overlap DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Overlap DTOs
 *
 * DDD: Application DTOs for Overlap use cases.
 */

import type { GetOverlapClusterParams, ListOverlapClustersParams } from "@portiva/core/overlap/types";

export type ListOverlapClustersInput = ListOverlapClustersParams;

export type GetOverlapClusterInput = GetOverlapClusterParams;

export type ListOverlapClustersOutput = {};

export type GetOverlapClusterOutput = {};
