/**
 * ListGate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListStageGatesParams } from "@portiva/core/gate";

export function createListGateRequest(overrides: Partial<ListStageGatesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
