/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Overlap Domain Use Cases
 * 
 * List of all use case names for the overlap domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const OVERLAP_USE_CASES = [
  "executeGetOverlapCluster",
  "executeKeepOverlapDifferentiated",
  "executeKillOverlapMember",
  "executeListOverlapClusters",
  "executeMergeOverlapCluster"
] as const;
