/**
 * Routes for PolicyWatch
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-watch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPolicyWatchItem, getPolicyWatchItem, listPolicyWatchItems } from "../handlers/policy-watch.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function policyWatchRoutes(fastify: FastifyInstance) {
  // POST /v1/policy-watch (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/policy-watch",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPolicyWatchDependenciesForRequest();
        await createPolicyWatchItem(request, reply, deps);
      });
    }
  );


  // GET /v1/policy-watch (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policy-watch",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPolicyWatchDependenciesForRequest();
        await listPolicyWatchItems(request, reply, deps);
      });
    }
  );


  // GET /v1/policy-watch/{policyWatchId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/policy-watch/:policyWatchId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyWatchId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPolicyWatchDependenciesForRequest();
        await getPolicyWatchItem(request, reply, deps);
      });
    }
  );


}
