/**
 * GetOverlapCluster handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getOverlapCluster } from "@portiva/api-server/domains/overlap/handlers";
import type { OverlapDDDDependencies } from "@portiva/api-server/domains/overlap";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { OVERLAP_USE_CASES } from "../__factories__/use-cases.js";

describe("GetOverlapCluster", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: OverlapDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<OverlapDDDDependencies>(
      OVERLAP_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetOverlapCluster, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { overlapClusterId: entity.id };

    await getOverlapCluster(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetOverlapCluster.execute).toHaveBeenCalledWith(expect.objectContaining({ overlapClusterId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { overlapClusterId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetOverlapCluster, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getOverlapCluster(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
