/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @portiva/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@portiva/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@portiva/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@portiva/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@portiva/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@portiva/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _boardPack from "./board-pack/index.js";
import * as _decision from "./decision/index.js";
import * as _dependency from "./dependency/index.js";
import * as _gate from "./gate/index.js";
import * as _identity from "./identity/index.js";
import * as _initiative from "./initiative/index.js";
import * as _overlap from "./overlap/index.js";
import * as _policyWatch from "./policy-watch/index.js";
import * as _scorecard from "./scorecard/index.js";

// Export as namespaces
export const _shared = __shared;
export const boardPack = _boardPack;
export const decision = _decision;
export const dependency = _dependency;
export const gate = _gate;
export const identity = _identity;
export const initiative = _initiative;
export const overlap = _overlap;
export const policyWatch = _policyWatch;
export const scorecard = _scorecard;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@portiva/core"; activity.types.*
//   - Direct exports: import * from "@portiva/core/activity/types/index.js"
//   - Direct exports: import * from "@portiva/core/activity/repositories/index.js"
//   - Direct exports: import * from "@portiva/core/activity/models/index.js"
//   - Direct exports: import * from "@portiva/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// BoardPack Service
export { schemas as BoardPackSchemas } from "./board-pack/schemas/board-pack.schemas.js";

// Decision Service
export { schemas as DecisionSchemas } from "./decision/schemas/decision.schemas.js";

// Dependency Service
export { schemas as DependencySchemas } from "./dependency/schemas/dependency.schemas.js";

// Gate Service
export { schemas as GateSchemas } from "./gate/schemas/gate.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Initiative Service
export { schemas as InitiativeSchemas } from "./initiative/schemas/initiative.schemas.js";

// Overlap Service
export { schemas as OverlapSchemas } from "./overlap/schemas/overlap.schemas.js";

// PolicyWatch Service
export { schemas as PolicyWatchSchemas } from "./policy-watch/schemas/policy-watch.schemas.js";

// Scorecard Service
export { schemas as ScorecardSchemas } from "./scorecard/schemas/scorecard.schemas.js";

