/**
 * Initiative Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/initiative.openapi.types.js";
import { schemas } from "../schemas/initiative.schemas.js";

/**
 * Entity: InitiativeEntity
 * Description: Represents the Initiative domain model.
 * Source: schemas.Initiative
 * Type: Domain Entity (API)
 */
export const InitiativeEntitySchema = schemas.Initiative;
export type InitiativeEntity = components["schemas"]["Initiative"];
