/**
 * ConcentrationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependency
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConcentrationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConcentrationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConcentrationRepository,
} from "@portiva/services/dependency";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConcentrationRepositoryDdb } from "./concentration-repository.ddb.js";

/**
 * ConcentrationRepositoryAdapter
 *
 * Implements ConcentrationRepository port for infrastructure layer.
 */
export class ConcentrationRepositoryAdapter implements ConcentrationRepository {
  private readonly ddb: ConcentrationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConcentrationRepositoryDdb(this.dynamoClient);
  }

  async getDependencyConcentration(input: Parameters<ConcentrationRepository['getDependencyConcentration']>[0]): Promise<Awaited<ReturnType<ConcentrationRepository['getDependencyConcentration']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDependencyConcentration(input);
  }
}
