/**
 * DependencyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependency
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DependencyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DependencyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DependencyRepository,
} from "@portiva/services/dependency";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DependencyRepositoryDdb } from "./dependency-repository.ddb.js";

/**
 * DependencyRepositoryAdapter
 *
 * Implements DependencyRepository port for infrastructure layer.
 */
export class DependencyRepositoryAdapter implements DependencyRepository {
  private readonly ddb: DependencyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DependencyRepositoryDdb(this.dynamoClient);
  }

  async listVendorDependencies(input: Parameters<DependencyRepository['listVendorDependencies']>[0]): Promise<Awaited<ReturnType<DependencyRepository['listVendorDependencies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listVendorDependencies(input);
  }

  async createVendorDependency(input: Parameters<DependencyRepository['createVendorDependency']>[0]): Promise<Awaited<ReturnType<DependencyRepository['createVendorDependency']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createVendorDependency(input);
  }

  async getVendorDependency(input: Parameters<DependencyRepository['getVendorDependency']>[0]): Promise<Awaited<ReturnType<DependencyRepository['getVendorDependency']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getVendorDependency(input);
  }
}
