/**
 * Handlers for Gate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GateDomainModule } from "../dependencies/gate-ddd.dependencies.js";
import type { CreateStageGateInput, GetStageGateInput, ListStageGatesInput } from "@portiva/services/gate";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/gates
 * Operation: listStageGates
 */
export async function listStageGates(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], initiativeId?: string | string[], status?: string | string[], fromStage?: string | string[], toStage?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GateDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListStageGatesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.gates.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/gates
 * Operation: createStageGate
 */
export async function createStageGate(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GateDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateStageGateInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.gates.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/gates/{gateId}
 * Operation: getStageGate
 */
export async function getStageGate(
  request: FastifyRequest<{ Params: { gateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GateDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetStageGateInput = {
    gateId: request.params.gateId,
  };
  const result = await deps.useCases.gates.get.execute(input);
  return reply.code(200).send(result);
}


