/**
 * Routes for KillMember
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { killOverlapMember } from "../handlers/kill-member.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function killMemberRoutes(fastify: FastifyInstance) {
  // POST /v1/overlaps/{overlapClusterId}/kill-member (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/overlaps/:overlapClusterId/kill-member",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { overlapClusterId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getOverlapDependenciesForRequest();
        await killOverlapMember(request, reply, deps);
      });
    }
  );


}
