/**
 * Scorecard DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Scorecard DTOs
 *
 * DDD: Application DTOs for Scorecard use cases.
 */

import type { GetScorecardByInitiativeParams, GetScorecardParams, ListScorecardsParams, UpsertScorecardRequestInput } from "@portiva/core/scorecard/types";

export type ListScorecardsInput = ListScorecardsParams;

export type UpsertScorecardInput = UpsertScorecardRequestInput;

export type GetScorecardInput = GetScorecardParams;

export type GetScorecardByInitiativeInput = GetScorecardByInitiativeParams;

export type ListScorecardsOutput = {};

export type UpsertScorecardOutput = {};

export type GetScorecardOutput = {};

export type GetScorecardByInitiativeOutput = {};
