/**
 * BoardPackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BoardPackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BoardPackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BoardPackRepository,
} from "@portiva/services/board-pack";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BoardPackRepositoryDdb } from "./board-pack-repository.ddb.js";

/**
 * BoardPackRepositoryAdapter
 *
 * Implements BoardPackRepository port for infrastructure layer.
 */
export class BoardPackRepositoryAdapter implements BoardPackRepository {
  private readonly ddb: BoardPackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BoardPackRepositoryDdb(this.dynamoClient);
  }

  async listBoardPacks(input: Parameters<BoardPackRepository['listBoardPacks']>[0]): Promise<Awaited<ReturnType<BoardPackRepository['listBoardPacks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBoardPacks(input);
  }

  async createBoardPack(input: Parameters<BoardPackRepository['createBoardPack']>[0]): Promise<Awaited<ReturnType<BoardPackRepository['createBoardPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createBoardPack(input);
  }

  async getBoardPack(input: Parameters<BoardPackRepository['getBoardPack']>[0]): Promise<Awaited<ReturnType<BoardPackRepository['getBoardPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getBoardPack(input);
  }
}
