/**
 * GetScorecardByInitiative handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getScorecardByInitiative } from "@portiva/api-server/domains/scorecard/handlers";
import type { ScorecardDDDDependencies } from "@portiva/api-server/domains/scorecard";
import { createScorecard as createScorecardEntity } from "@portiva/factories/scorecard";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { SCORECARD_USE_CASES } from "../__factories__/use-cases.js";

describe("GetScorecardByInitiative", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ScorecardDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ScorecardDDDDependencies>(
      SCORECARD_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createScorecardEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetScorecardByInitiative, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { initiativeId: entity.id };

    await getScorecardByInitiative(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetScorecardByInitiative.execute).toHaveBeenCalledWith(expect.objectContaining({ initiativeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { initiativeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetScorecardByInitiative, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getScorecardByInitiative(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
