/**
 * UpsertScorecard handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { upsertScorecard } from "@portiva/api-server/domains/scorecard/handlers";
import type { ScorecardDDDDependencies } from "@portiva/api-server/domains/scorecard";
import { createScorecard as createScorecardEntity } from "@portiva/factories/scorecard";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { SCORECARD_USE_CASES } from "../__factories__/use-cases.js";

describe("UpsertScorecard", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ScorecardDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ScorecardDDDDependencies>(
      SCORECARD_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createScorecardEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { id: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpsertScorecard, "execute").mockResolvedValue(useCaseResult);

    await upsertScorecard(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpsertScorecard.execute).toHaveBeenCalledWith(expect.objectContaining({ id: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
