/**
 * DependencyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependency
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DependencyRepository Port
 *
 * DDD: Application port for dependencyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateVendorDependencyInput, CreateVendorDependencyOutput, GetVendorDependencyInput, GetVendorDependencyOutput, ListVendorDependenciesInput, ListVendorDependenciesOutput } from "../dto/dependency.dto";
export interface DependencyRepository {
  listVendorDependencies(input: ListVendorDependenciesInput): Promise<ListVendorDependenciesOutput>;
  createVendorDependency(input: CreateVendorDependencyInput): Promise<CreateVendorDependencyOutput>;
  getVendorDependency(input: GetVendorDependencyInput): Promise<GetVendorDependencyOutput>;
}

export type { CreateVendorDependencyInput, CreateVendorDependencyOutput, GetVendorDependencyInput, GetVendorDependencyOutput, ListVendorDependenciesInput, ListVendorDependenciesOutput } from "../dto/dependency.dto";
