/**
 * Routes for Initiative
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createInitiative, getInitiative, listInitiatives, updateInitiative } from "../handlers/initiative.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function initiativeRoutes(fastify: FastifyInstance) {
  // POST /v1/initiatives (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/initiatives",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInitiativeDependenciesForRequest();
        await createInitiative(request, reply, deps);
      });
    }
  );


  // GET /v1/initiatives (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/initiatives",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInitiativeDependenciesForRequest();
        await listInitiatives(request, reply, deps);
      });
    }
  );


  // GET /v1/initiatives/{initiativeId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/initiatives/:initiativeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { initiativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInitiativeDependenciesForRequest();
        await getInitiative(request, reply, deps);
      });
    }
  );


  // PATCH /v1/initiatives/{initiativeId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/initiatives/:initiativeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { initiativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInitiativeDependenciesForRequest();
        await updateInitiative(request, reply, deps);
      });
    }
  );


}
