/**
 * ExecuteListStageGates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListStageGates Use Case
 *
 * DDD: Application use case for list Gate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListStageGatesInput, ListStageGatesOutput } from "../dto/gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { GateRepository } from "../ports";

export class ExecuteListStageGates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly gate: GateRepository
  ) {}

  async execute(input: ListStageGatesInput): Promise<ListStageGatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.gatId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.gate.listStageGates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListStageGatesOutput;
  }
}
