/**
 * ExecuteCreateStageGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateStageGate Use Case
 *
 * DDD: Application use case for create Gate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateStageGateInput, CreateStageGateOutput } from "../dto/gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { GateRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateStageGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly gate: GateRepository
  ) {}

  async execute(input: CreateStageGateInput): Promise<CreateStageGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.gatId();

    // All field names extracted from OpenAPI spec: fromStage, initiativeId, killMetrics, toStage
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.initiativeId) {
      throw new ValidationError("initiativeId is required");
    }
    if (!input.fromStage) {
      throw new ValidationError("fromStage is required");
    }
    if (!input.killMetrics) {
      throw new ValidationError("killMetrics is required");
    }
    if (!input.toStage) {
      throw new ValidationError("toStage is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (gate domain)
    const entityId = this.idGenerator.gatId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.gate.createStageGate({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateStageGateOutput;
  }
}
