/**
 * MergeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MergeRepository Port
 *
 * DDD: Application port for mergerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { MergeOverlapClusterInput, MergeOverlapClusterOutput } from "../dto/merge.dto";
export interface MergeRepository {
  mergeOverlapCluster(input: MergeOverlapClusterInput): Promise<MergeOverlapClusterOutput>;
}

export type { MergeOverlapClusterInput, MergeOverlapClusterOutput } from "../dto/merge.dto";
