/**
 * OverlapRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OverlapRepository Port
 *
 * DDD: Application port for overlaprepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetOverlapClusterInput, GetOverlapClusterOutput, ListOverlapClustersInput, ListOverlapClustersOutput } from "../dto/overlap.dto";
export interface OverlapRepository {
  listOverlapClusters(input: ListOverlapClustersInput): Promise<ListOverlapClustersOutput>;
  getOverlapCluster(input: GetOverlapClusterInput): Promise<GetOverlapClusterOutput>;
}

export type { GetOverlapClusterInput, GetOverlapClusterOutput, ListOverlapClustersInput, ListOverlapClustersOutput } from "../dto/overlap.dto";
