/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildBoardPackDomainModule } from "./board-pack/dependencies/board-pack-ddd.dependencies.js";
export { buildDecisionDomainModule } from "./decision/dependencies/decision-ddd.dependencies.js";
export { buildDependencyDomainModule } from "./dependency/dependencies/dependency-ddd.dependencies.js";
export { buildGateDomainModule } from "./gate/dependencies/gate-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildInitiativeDomainModule } from "./initiative/dependencies/initiative-ddd.dependencies.js";
export { buildOverlapDomainModule } from "./overlap/dependencies/overlap-ddd.dependencies.js";
export { buildPolicyWatchDomainModule } from "./policy-watch/dependencies/policy-watch-ddd.dependencies.js";
export { buildScorecardDomainModule } from "./scorecard/dependencies/scorecard-ddd.dependencies.js";

// Export all domain dependency types
export type { BoardPackDomainModule } from "./board-pack/dependencies/board-pack-ddd.dependencies.js";
export type { DecisionDomainModule } from "./decision/dependencies/decision-ddd.dependencies.js";
export type { DependencyDomainModule } from "./dependency/dependencies/dependency-ddd.dependencies.js";
export type { GateDomainModule } from "./gate/dependencies/gate-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { InitiativeDomainModule } from "./initiative/dependencies/initiative-ddd.dependencies.js";
export type { OverlapDomainModule } from "./overlap/dependencies/overlap-ddd.dependencies.js";
export type { PolicyWatchDomainModule } from "./policy-watch/dependencies/policy-watch-ddd.dependencies.js";
export type { ScorecardDomainModule } from "./scorecard/dependencies/scorecard-ddd.dependencies.js";
