/**
 * ListDependency DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependency
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListVendorDependenciesParams } from "@portiva/core/dependency";

export function createListDependencyRequest(overrides: Partial<ListVendorDependenciesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
