/**
 * ListScorecard DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListScorecardsParams } from "@portiva/core/scorecard";

export function createListScorecardRequest(overrides: Partial<ListScorecardsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
