/**
 * ExecuteCreateVendorDependency - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: dependency
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateVendorDependency Use Case
 *
 * DDD: Application use case for create Dependency.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateVendorDependencyInput, CreateVendorDependencyOutput } from "../dto/dependency.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { DependencyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateVendorDependency {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dependency: DependencyRepository
  ) {}

  async execute(input: CreateVendorDependencyInput): Promise<CreateVendorDependencyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.depId();

    // All field names extracted from OpenAPI spec: capability, criticality, initiativeId, mitigationNotes, vendorName
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.vendorName) {
      throw new ValidationError("vendorName is required");
    }
    if (!input.capability) {
      throw new ValidationError("capability is required");
    }
    if (!input.criticality) {
      throw new ValidationError("criticality is required");
    }
    if (!input.initiativeId) {
      throw new ValidationError("initiativeId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (dependency domain)
    const entityId = this.idGenerator.depId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.dependency.createVendorDependency({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateVendorDependencyOutput;
  }
}
