/**
 * ExceptionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExceptionRepository Port
 *
 * DDD: Application port for exceptionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExceptionStageGateInput, ExceptionStageGateOutput } from "../dto/exception.dto";
export interface ExceptionRepository {
  exceptionStageGate(input: ExceptionStageGateInput): Promise<ExceptionStageGateOutput>;
}

export type { ExceptionStageGateInput, ExceptionStageGateOutput } from "../dto/exception.dto";
