/**
 * PassRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PassRepository Port
 *
 * DDD: Application port for passrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PassStageGateInput, PassStageGateOutput } from "../dto/pass.dto";
export interface PassRepository {
  passStageGate(input: PassStageGateInput): Promise<PassStageGateOutput>;
}

export type { PassStageGateInput, PassStageGateOutput } from "../dto/pass.dto";
