/**
 * PauseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PauseRepository Port
 *
 * DDD: Application port for pauserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { PauseStageGateInput, PauseStageGateOutput } from "../dto/pause.dto";
export interface PauseRepository {
  pauseStageGate(input: PauseStageGateInput): Promise<PauseStageGateOutput>;
}

export type { PauseStageGateInput, PauseStageGateOutput } from "../dto/pause.dto";
