/**
 * PublishBoardPack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { publishBoardPack } from "@portiva/api-server/domains/board-pack/handlers";
import type { BoardPackDDDDependencies } from "@portiva/api-server/domains/board-pack";
import { createCreatePublishRequest } from "@portiva/factories/board-pack";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { BOARDPACK_USE_CASES } from "../__factories__/use-cases.js";

describe("PublishBoardPack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BoardPackDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BoardPackDDDDependencies>(
      BOARDPACK_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreatePublishRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePublishBoardPack, "execute").mockResolvedValue(useCaseResult);

    await publishBoardPack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePublishBoardPack.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
