/**
 * ScorecardRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScorecardRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ScorecardRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ScorecardRepository,
} from "@portiva/services/scorecard";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ScorecardRepositoryDdb } from "./scorecard-repository.ddb.js";

/**
 * ScorecardRepositoryAdapter
 *
 * Implements ScorecardRepository port for infrastructure layer.
 */
export class ScorecardRepositoryAdapter implements ScorecardRepository {
  private readonly ddb: ScorecardRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ScorecardRepositoryDdb(this.dynamoClient);
  }

  async listScorecards(input: Parameters<ScorecardRepository['listScorecards']>[0]): Promise<Awaited<ReturnType<ScorecardRepository['listScorecards']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listScorecards(input);
  }

  async upsertScorecard(input: Parameters<ScorecardRepository['upsertScorecard']>[0]): Promise<Awaited<ReturnType<ScorecardRepository['upsertScorecard']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.upsertScorecard(input);
  }

  async getScorecard(input: Parameters<ScorecardRepository['getScorecard']>[0]): Promise<Awaited<ReturnType<ScorecardRepository['getScorecard']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getScorecard(input);
  }

  async getScorecardByInitiative(input: Parameters<ScorecardRepository['getScorecardByInitiative']>[0]): Promise<Awaited<ReturnType<ScorecardRepository['getScorecardByInitiative']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getScorecardByInitiative(input);
  }
}
