/**
 * Handlers for PolicyWatch
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-watch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PolicyWatchDomainModule } from "../dependencies/policy-watch-ddd.dependencies.js";
import type { CreatePolicyWatchItemInput, GetPolicyWatchItemInput, ListPolicyWatchItemsInput } from "@portiva/services/policy-watch";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/policy-watch
 * Operation: listPolicyWatchItems
 */
export async function listPolicyWatchItems(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], blocksScale?: string | string[], initiativeId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PolicyWatchDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPolicyWatchItemsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.policyWatches.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/policy-watch
 * Operation: createPolicyWatchItem
 */
export async function createPolicyWatchItem(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PolicyWatchDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreatePolicyWatchItemInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.policyWatches.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/policy-watch/{policyWatchId}
 * Operation: getPolicyWatchItem
 */
export async function getPolicyWatchItem(
  request: FastifyRequest<{ Params: { policyWatchId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PolicyWatchDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPolicyWatchItemInput = {
    policyWatchId: request.params.policyWatchId,
  };
  const result = await deps.useCases.policyWatches.get.execute(input);
  return reply.code(200).send(result);
}


