/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-watch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * PolicyWatch Domain Use Cases
 * 
 * List of all use case names for the policy-watch domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const POLICYWATCH_USE_CASES = [
  "executeCreatePolicyWatchItem",
  "executeGetPolicyWatchItem",
  "executeListPolicyWatchItems",
  "executeResolvePolicyWatchItem",
  "executeWaivePolicyWatchItem"
] as const;
