/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-funding-decision.handler.test.js";
export * from "./get-funding-decision.handler.test.js";
export * from "./list-funding-decisions.handler.test.js";
