/**
 * GetBoardPack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getBoardPack } from "@portiva/api-server/domains/board-pack/handlers";
import type { BoardPackDDDDependencies } from "@portiva/api-server/domains/board-pack";
import { createBoardPack as createBoardPackEntity } from "@portiva/factories/board-pack";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { BOARDPACK_USE_CASES } from "../__factories__/use-cases.js";

describe("GetBoardPack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BoardPackDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BoardPackDDDDependencies>(
      BOARDPACK_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createBoardPackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetBoardPack, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { boardPackId: entity.id };

    await getBoardPack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetBoardPack.execute).toHaveBeenCalledWith(expect.objectContaining({ boardPackId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { boardPackId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetBoardPack, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getBoardPack(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
