/**
 * ListBoardPacks handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listBoardPacks } from "@portiva/api-server/domains/board-pack/handlers";
import type { BoardPackDDDDependencies } from "@portiva/api-server/domains/board-pack";
import { createBoardPack as createBoardPackEntity } from "@portiva/factories/board-pack";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@portiva/tests/shared";
import { BOARDPACK_USE_CASES } from "../__factories__/use-cases.js";

describe("ListBoardPacks", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BoardPackDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BoardPackDDDDependencies>(
      BOARDPACK_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createBoardPackEntity({ orgId }),
      createBoardPackEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListBoardPacks, "execute").mockResolvedValue(useCaseResult);

    await listBoardPacks(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListBoardPacks.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
