/**
 * Overlap DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: overlap
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Overlap Domain Module - Composition root
 *
 * DDD: Composition root for overlap domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  KeepDifferentiatedRepositoryAdapter,
  KillMemberRepositoryAdapter,
  MergeRepositoryAdapter,
  OverlapRepositoryAdapter,
} from "@portiva/adapters/overlap";
import { getIdGeneratorService } from "@portiva/adapters";
import type { AdapterDynamoDBClient } from "@portiva/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetOverlapCluster,
  ExecuteListOverlapClusters,
} from "@portiva/services/overlap/usecases";
// Ports (interfaces)
import type {
  KeepDifferentiatedRepository,
  KillMemberRepository,
  MergeRepository,
  OverlapRepository,
} from "@portiva/services/overlap/ports";

export interface OverlapDomainModule {
  repos: {
    keepDifferentiateds: KeepDifferentiatedRepository;
    killMembers: KillMemberRepository;
    merges: MergeRepository;
    overlaps: OverlapRepository;
  };
  useCases: {
    overlaps: {
      get: ExecuteGetOverlapCluster;
      list: ExecuteListOverlapClusters;
    };
  };
}

export function buildOverlapDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): OverlapDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      keepDifferentiateds?: KeepDifferentiatedRepository;
      killMembers?: KillMemberRepository;
      merges?: MergeRepository;
      overlaps?: OverlapRepository;
    } = {};

    obj.keepDifferentiateds = new KeepDifferentiatedRepositoryAdapter(dynamoClient);
    obj.killMembers = new KillMemberRepositoryAdapter(dynamoClient);
    obj.merges = new MergeRepositoryAdapter(dynamoClient);
    obj.overlaps = new OverlapRepositoryAdapter(dynamoClient);
    return {
      keepDifferentiateds: obj.keepDifferentiateds!,
      killMembers: obj.killMembers!,
      merges: obj.merges!,
      overlaps: obj.overlaps!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    overlaps: {
      get: new ExecuteGetOverlapCluster(executionContext, idGenerator, repos.overlaps),
      list: new ExecuteListOverlapClusters(executionContext, idGenerator, repos.overlaps),
    },
  };
  return { repos, useCases: useCases as OverlapDomainModule["useCases"] };
}
