/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Scorecard Domain Use Cases
 * 
 * List of all use case names for the scorecard domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SCORECARD_USE_CASES = [
  "executeGetScorecard",
  "executeGetScorecardByInitiative",
  "executeListScorecards",
  "executeUpsertScorecard"
] as const;
