/**
 * ExecuteUpdateInitiative - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateInitiative Use Case
 *
 * DDD: Application use case for update Initiative.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateInitiativeInput, UpdateInitiativeOutput } from "../dto/initiative.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { InitiativeRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateInitiative {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly initiative: InitiativeRepository
  ) {}

  async execute(input: UpdateInitiativeInput): Promise<UpdateInitiativeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.iniId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).initiativeId) {
      throw new ValidationError("initiativeId is required");
    }
    const initiativeId = (input as any).initiativeId;

    // Load existing entity
    const existing = await this.initiative.getInitiative({ initiativeId: initiativeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${initiativeId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.initiative.updateInitiative({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateInitiativeOutput;
  }
}
