/**
 * ExecuteListInitiatives - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListInitiatives Use Case
 *
 * DDD: Application use case for list Initiative.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListInitiativesInput, ListInitiativesOutput } from "../dto/initiative.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { InitiativeRepository } from "../ports";

export class ExecuteListInitiatives {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly initiative: InitiativeRepository
  ) {}

  async execute(input: ListInitiativesInput): Promise<ListInitiativesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.iniId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.initiative.listInitiatives({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListInitiativesOutput;
  }
}
