/**
 * ExecuteCreateInitiative - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: initiative
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateInitiative Use Case
 *
 * DDD: Application use case for create Initiative.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateInitiativeInput, CreateInitiativeOutput } from "../dto/initiative.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { InitiativeRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateInitiative {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly initiative: InitiativeRepository
  ) {}

  async execute(input: CreateInitiativeInput): Promise<CreateInitiativeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.iniId();

    // All field names extracted from OpenAPI spec: arcs, economicBuyer, name, outcomeMetric, ownerUserId, sponsorUserId, stage, thesis
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.economicBuyer) {
      throw new ValidationError("economicBuyer is required");
    }
    if (!input.arcs) {
      throw new ValidationError("arcs is required");
    }
    if (!input.ownerUserId) {
      throw new ValidationError("ownerUserId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (initiative domain)
    const entityId = this.idGenerator.iniId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.initiative.createInitiative({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateInitiativeOutput;
  }
}
