/**
 * Routes for Kill
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { killStageGate } from "../handlers/kill.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function killRoutes(fastify: FastifyInstance) {
  // POST /v1/gates/{gateId}/kill (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/gates/:gateId/kill",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { gateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGateDependenciesForRequest();
        await killStageGate(request, reply, deps);
      });
    }
  );


}
