/**
 * GateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gate
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements GateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  GateRepository,
} from "@portiva/services/gate";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { GateRepositoryDdb } from "./gate-repository.ddb.js";

/**
 * GateRepositoryAdapter
 *
 * Implements GateRepository port for infrastructure layer.
 */
export class GateRepositoryAdapter implements GateRepository {
  private readonly ddb: GateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new GateRepositoryDdb(this.dynamoClient);
  }

  async listStageGates(input: Parameters<GateRepository['listStageGates']>[0]): Promise<Awaited<ReturnType<GateRepository['listStageGates']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listStageGates(input);
  }

  async createStageGate(input: Parameters<GateRepository['createStageGate']>[0]): Promise<Awaited<ReturnType<GateRepository['createStageGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createStageGate(input);
  }

  async getStageGate(input: Parameters<GateRepository['getStageGate']>[0]): Promise<Awaited<ReturnType<GateRepository['getStageGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getStageGate(input);
  }
}
