/**
 * Domain Dependency Injection Hook
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Performance-optimized centralized dependency injection that matches domain from path
 * and injects only the needed domain dependencies. Dependencies are cached per domain.
 *
 * Usage:
 * ```typescript
 * fastify.addHook("preHandler", injectDomainDependencies);
 * ```
 *
 * Access dependencies in routes:
 * ```typescript
 * const deps = getDomainDeps(request, "content");
 * ```
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AdapterDynamoDBClient } from "@portiva/adapters";
import {
  DynamoDBClient,
  BatchWriteItemCommand,
} from "@aws-sdk/client-dynamodb";
import {
  DynamoDBDocumentClient,
  QueryCommand,
  GetCommand,
  PutCommand,
  UpdateCommand,
  DeleteCommand,
  ScanCommand,
  TransactWriteCommand,
} from "@aws-sdk/lib-dynamodb";
import type {
  QueryCommandInput,
  QueryCommandOutput,
  GetCommandInput,
  GetCommandOutput,
  PutCommandInput,
  PutCommandOutput,
  UpdateCommandInput,
  UpdateCommandOutput,
  DeleteCommandInput,
  DeleteCommandOutput,
  ScanCommandInput,
  ScanCommandOutput,
  TransactWriteCommandInput,
  TransactWriteCommandOutput,
} from "@aws-sdk/lib-dynamodb";
import type {
  BatchWriteItemCommandInput,
  BatchWriteItemCommandOutput,
} from "@aws-sdk/client-dynamodb";
import { getAwsCredentialProvider } from "../infrastructure/aws-credentials.js";

// Import all domain builder functions and types from barrel export
import {
  buildBoardPackDomainModule,
  buildDecisionDomainModule,
  buildDependencyDomainModule,
  buildGateDomainModule,
  buildIdentityDomainModule,
  buildInitiativeDomainModule,
  buildOverlapDomainModule,
  buildPolicyWatchDomainModule,
  buildScorecardDomainModule,
} from "../../domains/index.js";
import type {
  BoardPackDomainModule,
  DecisionDomainModule,
  DependencyDomainModule,
  GateDomainModule,
  IdentityDomainModule,
  InitiativeDomainModule,
  OverlapDomainModule,
  PolicyWatchDomainModule,
  ScorecardDomainModule,
} from "../../domains/index.js";

/**
 * Performance-optimized dependency cache
 */
const dependencyCache = new Map<string, any>();

function getCacheKey(domain: string): string {
  return domain;
}

/**
 * Wrapper for DynamoDBDocumentClient that implements AdapterDynamoDBClient interface
 */
class DynamoDBClientAdapter implements AdapterDynamoDBClient {
  constructor(private readonly docClient: DynamoDBDocumentClient) {}

  async query(input: QueryCommandInput): Promise<QueryCommandOutput> {
    return this.docClient.send(new QueryCommand(input));
  }

  async get(input: GetCommandInput): Promise<GetCommandOutput> {
    return this.docClient.send(new GetCommand(input));
  }

  async put(input: PutCommandInput): Promise<PutCommandOutput> {
    return this.docClient.send(new PutCommand(input));
  }

  async update(input: UpdateCommandInput): Promise<UpdateCommandOutput> {
    return this.docClient.send(new UpdateCommand(input));
  }

  async delete(input: DeleteCommandInput): Promise<DeleteCommandOutput> {
    return this.docClient.send(new DeleteCommand(input));
  }

  async scan(input: ScanCommandInput): Promise<ScanCommandOutput> {
    return this.docClient.send(new ScanCommand(input));
  }

  async batchWrite(
    input: BatchWriteItemCommandInput,
  ): Promise<BatchWriteItemCommandOutput> {
    return this.docClient.send(new BatchWriteItemCommand(input));
  }

  async transactWrite(
    input: TransactWriteCommandInput,
  ): Promise<TransactWriteCommandOutput> {
    return this.docClient.send(new TransactWriteCommand(input));
  }

  async send<T>(command: T): Promise<any> {
    return this.docClient.send(command as any);
  }
}

let dynamoClientInstance: AdapterDynamoDBClient | null = null;

export function getDynamoClientInstance(): AdapterDynamoDBClient {
  if (!dynamoClientInstance) {
    const region =
      process.env.AWS_REGION || process.env.AWS_DEFAULT_REGION || "us-east-1";
    const clientConfig: {
      region: string;
      endpoint?: string;
      credentials?: import("@aws-sdk/types").AwsCredentialIdentityProvider;
    } = { region };

    const credentialProvider = getAwsCredentialProvider();
    if (credentialProvider) clientConfig.credentials = credentialProvider;

    if (process.env.AWS_ENDPOINT_URL || process.env.LOCALSTACK_ENDPOINT) {
      clientConfig.endpoint =
        process.env.AWS_ENDPOINT_URL || process.env.LOCALSTACK_ENDPOINT;
    }

    const client = new DynamoDBClient(clientConfig);
    const docClient = DynamoDBDocumentClient.from(client);
    dynamoClientInstance = new DynamoDBClientAdapter(docClient);
  }
  return dynamoClientInstance;
}

/**
 * Domain path patterns - maps URL path segments to domain names
 */
const DOMAIN_PATH_PATTERNS: Array<{ pattern: RegExp; domain: string }> = [
  { pattern: /\/auth\//, domain: "identity" }, // Auth routes belong to identity domain
  { pattern: /\/board-pack\//, domain: "board-pack" },
  { pattern: /\/decision\//, domain: "decision" },
  { pattern: /\/dependency\//, domain: "dependency" },
  { pattern: /\/gate\//, domain: "gate" },
  { pattern: /\/identity\//, domain: "identity" },
  { pattern: /\/initiative\//, domain: "initiative" },
  { pattern: /\/overlap\//, domain: "overlap" },
  { pattern: /\/policy-watch\//, domain: "policy-watch" },
  { pattern: /\/scorecard\//, domain: "scorecard" },
];

function detectDomainFromPath(path: string): string | null {
  for (const { pattern, domain } of DOMAIN_PATH_PATTERNS) {
    if (pattern.test(path)) {
      return domain;
    }
  }
  return null;
}

/**
 * Inject domain dependencies into request object
 */
export async function injectDomainDependencies(
  request: FastifyRequest,
  reply: FastifyReply,
): Promise<void> {
  const orgId = (request as any).effectiveOrgId;

  if (!orgId) {
    reply.status(401).send({
      error: "Unauthorized",
      message:
        "Missing orgId. setOrgContext hook must run before injectDomainDependencies.",
    });
    return;
  }

  const path = request.url;
  const domain = detectDomainFromPath(path);

  if (!domain) {
    return;
  }

  if (!(request as any).deps) {
    (request as any).deps = {};
  }

  const cacheKey = getCacheKey(domain);
  let domainDeps = dependencyCache.get(cacheKey);

  if (!domainDeps) {
    const dynamoClient = getDynamoClientInstance();

    switch (domain) {
      case "board-pack":
        domainDeps = buildBoardPackDomainModule(dynamoClient);
        break;
      case "decision":
        domainDeps = buildDecisionDomainModule(dynamoClient);
        break;
      case "dependency":
        domainDeps = buildDependencyDomainModule(dynamoClient);
        break;
      case "gate":
        domainDeps = buildGateDomainModule(dynamoClient);
        break;
      case "identity":
        domainDeps = buildIdentityDomainModule(dynamoClient);
        break;
      case "initiative":
        domainDeps = buildInitiativeDomainModule(dynamoClient);
        break;
      case "overlap":
        domainDeps = buildOverlapDomainModule(dynamoClient);
        break;
      case "policy-watch":
        domainDeps = buildPolicyWatchDomainModule(dynamoClient);
        break;
      case "scorecard":
        domainDeps = buildScorecardDomainModule(dynamoClient);
        break;
      default:
        return;
    }

    dependencyCache.set(cacheKey, domainDeps);
  }

  (request as any).deps[domain] = domainDeps;
}

/**
 * Type-safe helper to get domain dependencies from request
 */
export function getDomainDeps<T extends keyof DomainDependencies>(
  request: FastifyRequest,
  domain: T,
): DomainDependencies[T] {
  const deps = (request as any).deps;
  if (!deps || !deps[domain]) {
    throw new Error(
      `${domain} dependencies not found. Ensure injectDomainDependencies hook ran and path matches ${domain} domain.`,
    );
  }
  return deps[domain];
}

/**
 * Type definitions for domain dependencies
 */
export interface DomainDependencies {
  "board-pack": BoardPackDomainModule;
  decision: DecisionDomainModule;
  dependency: DependencyDomainModule;
  gate: GateDomainModule;
  identity: IdentityDomainModule;
  initiative: InitiativeDomainModule;
  overlap: OverlapDomainModule;
  "policy-watch": PolicyWatchDomainModule;
  scorecard: ScorecardDomainModule;
}

export function clearDomainDependencyCache(domain: string): void {
  const cacheKey = getCacheKey(domain);
  dependencyCache.delete(cacheKey);
}

export function clearAllDomainDependencyCaches(): void {
  dependencyCache.clear();
}

/**
 * Convenience helpers for each domain (type-safe)
 */
export function getBoardPackDeps(
  request: FastifyRequest,
): DomainDependencies["board-pack"] {
  return getDomainDeps(request, "board-pack");
}
export function getDecisionDeps(
  request: FastifyRequest,
): DomainDependencies["decision"] {
  return getDomainDeps(request, "decision");
}
export function getDependencyDeps(
  request: FastifyRequest,
): DomainDependencies["dependency"] {
  return getDomainDeps(request, "dependency");
}
export function getGateDeps(
  request: FastifyRequest,
): DomainDependencies["gate"] {
  return getDomainDeps(request, "gate");
}
export function getIdentityDeps(
  request: FastifyRequest,
): DomainDependencies["identity"] {
  return getDomainDeps(request, "identity");
}
export function getInitiativeDeps(
  request: FastifyRequest,
): DomainDependencies["initiative"] {
  return getDomainDeps(request, "initiative");
}
export function getOverlapDeps(
  request: FastifyRequest,
): DomainDependencies["overlap"] {
  return getDomainDeps(request, "overlap");
}
export function getPolicyWatchDeps(
  request: FastifyRequest,
): DomainDependencies["policy-watch"] {
  return getDomainDeps(request, "policy-watch");
}
export function getScorecardDeps(
  request: FastifyRequest,
): DomainDependencies["scorecard"] {
  return getDomainDeps(request, "scorecard");
}
