/**
 * Handlers for Scorecard
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: scorecard
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ScorecardDomainModule } from "../dependencies/scorecard-ddd.dependencies.js";
import type { GetScorecardByInitiativeInput, GetScorecardInput, ListScorecardsInput, UpsertScorecardInput } from "@portiva/services/scorecard";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/scorecards
 * Operation: listScorecards
 */
export async function listScorecards(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], initiativeId?: string | string[], competitivePosture?: string | string[], moatDeclaration?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ScorecardDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListScorecardsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.scorecards.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/scorecards
 * Operation: upsertScorecard
 */
export async function upsertScorecard(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ScorecardDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertScorecardInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.scorecards.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/scorecards/{scorecardId}
 * Operation: getScorecard
 */
export async function getScorecard(
  request: FastifyRequest<{ Params: { scorecardId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ScorecardDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetScorecardInput = {
    scorecardId: request.params.scorecardId,
  };
  const result = await deps.useCases.scorecards.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/initiatives/{initiativeId}/scorecard
 * Operation: getScorecardByInitiative
 */
export async function getScorecardByInitiative(
  request: FastifyRequest<{ Params: { initiativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ScorecardDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetScorecardByInitiativeInput = {
    initiativeId: request.params.initiativeId,
  };
  const result = await deps.useCases.scorecards.get.execute(input);
  return reply.code(200).send(result);
}


