/**
 * ExecuteGetFundingDecision - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetFundingDecision Use Case
 *
 * DDD: Application use case for get Decision.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetFundingDecisionInput, GetFundingDecisionOutput } from "../dto/decision.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { DecisionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetFundingDecision {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decision: DecisionRepository
  ) {}

  async execute(input: GetFundingDecisionInput): Promise<GetFundingDecisionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.decId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).decisionId) {
      throw new ValidationError("decisionId is required");
    }
    const decisionId = (input as any).decisionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.decision.getFundingDecision({ decisionId: decisionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${decisionId}`);
    }

    return entity as GetFundingDecisionOutput;
  }
}
