/**
 * ExecuteCreateFundingDecision - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: decision
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateFundingDecision Use Case
 *
 * DDD: Application use case for create Decision.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateFundingDecisionInput, CreateFundingDecisionOutput } from "../dto/decision.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { DecisionRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateFundingDecision {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly decision: DecisionRepository
  ) {}

  async execute(input: CreateFundingDecisionInput): Promise<CreateFundingDecisionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.decId();

    // All field names extracted from OpenAPI spec: amount, currency, decidedByUserId, decision, dissentNotes, initiativeId, rationale, talentReskillNotes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.rationale) {
      throw new ValidationError("rationale is required");
    }
    if (!input.decidedByUserId) {
      throw new ValidationError("decidedByUserId is required");
    }
    if (!input.initiativeId) {
      throw new ValidationError("initiativeId is required");
    }
    if (!input.decision) {
      throw new ValidationError("decision is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (decision domain)
    const entityId = this.idGenerator.decId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.decision.createFundingDecision({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateFundingDecisionOutput;
  }
}
