/**
 * Resolve DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-watch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Resolve DTOs
 *
 * DDD: Application DTOs for Resolve use cases.
 */

import type { ResolvePolicyWatchItemParams, ResolvePolicyWatchItemRequestInput } from "@portiva/core/policy-watch/types";

export type ResolvePolicyWatchItemInput = ResolvePolicyWatchItemParams & ResolvePolicyWatchItemRequestInput;

export type ResolvePolicyWatchItemOutput = {};
