/**
 * Waive DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: policy-watch
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Waive DTOs
 *
 * DDD: Application DTOs for Waive use cases.
 */

import type { WaivePolicyWatchItemParams, WaivePolicyWatchItemRequestInput } from "@portiva/core/policy-watch/types";

export type WaivePolicyWatchItemInput = WaivePolicyWatchItemParams & WaivePolicyWatchItemRequestInput;

export type WaivePolicyWatchItemOutput = {};
