/**
 * ExecuteGetBoardPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetBoardPack Use Case
 *
 * DDD: Application use case for get BoardPack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetBoardPackInput, GetBoardPackOutput } from "../dto/board-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { BoardPackRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetBoardPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly boardPack: BoardPackRepository
  ) {}

  async execute(input: GetBoardPackInput): Promise<GetBoardPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.brdId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).boardPackId) {
      throw new ValidationError("boardPackId is required");
    }
    const boardpackId = (input as any).boardPackId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.boardPack.getBoardPack({ boardPackId: boardpackId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${boardpackId}`);
    }

    return entity as GetBoardPackOutput;
  }
}
