/**
 * ExecuteCreateBoardPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateBoardPack Use Case
 *
 * DDD: Application use case for create BoardPack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateBoardPackInput, CreateBoardPackOutput } from "../dto/board-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@portiva/services/_shared/index.js";
import type { BoardPackRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateBoardPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly boardPack: BoardPackRepository
  ) {}

  async execute(input: CreateBoardPackInput): Promise<CreateBoardPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.brdId();

    // All field names extracted from OpenAPI spec: expectedValue, killCount, openPolicyBlockers, period, riskSummary, spendTotal, stageDistribution
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.period) {
      throw new ValidationError("period is required");
    }
    if (!input.riskSummary) {
      throw new ValidationError("riskSummary is required");
    }
    if (!input.stageDistribution) {
      throw new ValidationError("stageDistribution is required");
    }
    if (!input.expectedValue) {
      throw new ValidationError("expectedValue is required");
    }
    if (!input.spendTotal) {
      throw new ValidationError("spendTotal is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (board-pack domain)
    const entityId = this.idGenerator.brdId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.boardPack.createBoardPack({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateBoardPackOutput;
  }
}
