/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: board-pack
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the board-pack domain.
 * Use these factories in tests to create test data.
 */

export { createBoardPack } from "./board-pack/entity/board-pack.entity.factory.js";
export { createCreatePublishRequest } from "./publish/dto/create-publish.dto.factory.js";
